# Generated by Django 5.2.11 on 2026-02-12 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('instances_created', models.PositiveIntegerField(default=0)),
                ('instances_completed', models.PositiveIntegerField(default=0)),
                ('avg_completion_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_completion_percentage', models.FloatField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='checklists.checklisttemplate')),
            ],
            options={
                'db_table': 'checklist_usage_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['template', 'date'], name='checklist_u_templat_d80f43_idx')],
                'unique_together': {('template', 'date')},
            },
        ),
    ]
