version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://${POSTGRES_USER:-checkix}:${POSTGRES_PASSWORD:-checkix}@db:5432/${POSTGRES_DB:-checkix}
      - REDIS_URL=redis://redis:6379/0
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  celery_worker:
    volumes:
      - .:/app
    environment:
      - DEBUG=1

  celery_beat:
    volumes:
      - .:/app
    environment:
      - DEBUG=1

  nginx:
    ports:
      - "8080:80"
