# Generated by Django 5.2.11 on 2026-02-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=20)),
                ('users_synced', models.PositiveIntegerField(default=0)),
                ('groups_synced', models.PositiveIntegerField(default=0)),
                ('users_created', models.PositiveIntegerField(default=0)),
                ('groups_created', models.PositiveIntegerField(default=0)),
                ('users_updated', models.PositiveIntegerField(default=0)),
                ('groups_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'LDAP Sync Log',
                'verbose_name_plural': 'LDAP Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
