# Generated by Django 5.2.11 on 2026-02-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sequential_mode', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='folders.folder')),
                ('tags', models.ManyToManyField(blank=True, related_name='checklist_templates', to='tags.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checklist_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('changelog', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='checklists.checklisttemplate')),
            ],
            options={
                'db_table': 'checklist_versions',
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_template', to='checklists.checklistversion'),
        ),
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('placeholder_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('text', 'Text Input'), ('date', 'Date Picker'), ('number', 'Number Input'), ('checkbox', 'Checkbox')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='checklists.checklistversion')),
            ],
            options={
                'db_table': 'checklist_placeholders',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_halt', models.BooleanField(default=False)),
                ('halt_message', models.CharField(blank=True, max_length=500)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='checklists.checklistitem')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklistversion')),
                ('placeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='checklists.placeholder')),
            ],
            options={
                'db_table': 'checklist_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlaceholderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=200)),
                ('display_text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('placeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='checklists.placeholder')),
            ],
            options={
                'db_table': 'checklist_placeholder_options',
                'ordering': ['order'],
            },
        ),
    ]
