# Generated by Django 5.2.11 on 2026-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_alter_checklistitem_options_checklistitem_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
    ]
