# Generated by Django 5.2.11 on 2026-02-12 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('team', 'Team'), ('private', 'Private')], default='public', max_length=20)),
                ('preset_values', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_links', to='checklists.checklisttemplate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_run_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'run_links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['unique_id'], name='run_links_unique__d275d1_idx'), models.Index(fields=['checklist_template'], name='run_links_checkli_4669c8_idx'), models.Index(fields=['access_type'], name='run_links_access__b1cb6f_idx')],
            },
        ),
    ]
