# Generated by Django 5.2.11 on 2026-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
