# Generated by Django 5.2.11 on 2026-02-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
