# Generated by Django 5.2.11 on 2026-02-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklist_instances', '0001_initial'),
        ('checklists', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('template', 'Template Level'), ('item', 'Item Level'), ('runtime', 'Runtime Instance')], max_length=20)),
                ('assignee_type', models.CharField(choices=[('user', 'Specific User'), ('group', 'Group'), ('parameter', 'Parameter/Placeholder'), ('manager', 'Manager')], max_length=20)),
                ('assignee_parameter', models.CharField(blank=True, max_length=100)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('auto_notify', models.BooleanField(default=True)),
                ('assignee_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to='users.group')),
                ('assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
                ('checklist_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runtime_assignments', to='checklist_instances.checklistinstance')),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='checklists.checklistitem')),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='checklists.checklisttemplate')),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
