# Generated by Django 5.2.11 on 2026-02-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('devops', 'DevOps'), ('qa', 'QA'), ('hr', 'HR'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('compliance', 'Compliance'), ('general', 'General')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_templates', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_templates', to=settings.AUTH_USER_MODEL)),
                ('checklist_template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_template', to='checklists.checklisttemplate')),
            ],
            options={
                'db_table': 'community_templates',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('community_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='community.communitytemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_template_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communitytemplate',
            index=models.Index(fields=['status', 'category'], name='community_t_status_97e798_idx'),
        ),
        migrations.AddIndex(
            model_name='communitytemplate',
            index=models.Index(fields=['is_featured'], name='community_t_is_feat_a88e49_idx'),
        ),
        migrations.AddIndex(
            model_name='communitytemplate',
            index=models.Index(fields=['rating'], name='community_t_rating_2c6cd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templaterating',
            unique_together={('community_template', 'user')},
        ),
    ]
