# Generated by Django 5.2.11 on 2026-02-12 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('checklist_instances', '0001_initial'),
        ('checklists', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDueDateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(choices=[('checklist_start', 'Checklist Start'), ('item_completion', 'Item Completion'), ('parameter_value', 'Parameter'), ('calendar_event', 'Calendar Event')], max_length=30)),
                ('trigger_item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('trigger_parameter_name', models.CharField(blank=True, max_length=100)),
                ('offset_minutes', models.IntegerField(default=0)),
                ('business_days_only', models.BooleanField(default=False)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_date_rules', to='checklists.checklistitem')),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_date_rules', to='checklists.checklisttemplate')),
            ],
            options={
                'db_table': 'dynamic_due_date_rules',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('task_due_in', 'Task Due In'), ('task_overdue_by', 'Task Overdue'), ('task_completed', 'Task Completed'), ('task_status_changed', 'Status Changed'), ('checklist_completed', 'Checklist Completed'), ('task_assigned', 'Task Assigned')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='assignments.assignment')),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='checklists.checklistitem')),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='checklists.checklisttemplate')),
            ],
            options={
                'db_table': 'notification_rules',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('trigger_offset_minutes', models.IntegerField()),
                ('recipient_type', models.CharField(choices=[('assignee', 'Assignee'), ('group', 'Group'), ('custom', 'Custom Email')], max_length=20)),
                ('custom_email', models.EmailField(blank=True, max_length=254)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_body', models.TextField(blank=True)),
                ('notification_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='notifications.notificationrule')),
                ('recipient_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group')),
            ],
            options={
                'db_table': 'notification_sequences',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('checklist_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='checklist_instances.checklistinstance')),
                ('notification_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notificationsequence')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
