# Generated by Django 5.2.11 on 2026-02-17 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicduedaterule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_date_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
